project:
  type: book

execute:
  echo: true
  warning: true
  message: true
  freeze: auto

toc: true
toc-depth: 3
css: book.css
callout-icon: false
code-fold: show

book:
  title: "AUD Recovery Activities"
  author: Sarah Sant'ana
  site-url: https://github.io/jjcurtin/aud_support
  repo-url: https://github.com/jjcurtin/aud_support
  repo-branch: main
  repo-actions: [edit]
  page-navigation: true
  reader-mode: true
  chapters:
    - index.qmd
    - craving.qmd
    - affect.qmd

