project:
  type: book

execute:
  echo: true
  warning: true
  message: true
  freeze: auto

toc: true
toc-depth: 3
css: book.css
callout-icon: false
code-fold: show

book:
  title: "AUD Recovery Activities"
  author: Sarah Sant'ana
  site-url: https://github.io/jjcurtin/aud_support
  repo-url: https://github.com/jjcurtin/aud_support
  repo-branch: main
  repo-actions: [edit]
  page-navigation: true
  reader-mode: true
  chapters:
    - index.qmd
    - notes.qmd
    - craving.qmd
    - affect_arousal.qmd
    - abstinence_goal.qmd
    - past_use.qmd
    - future_use.qmd
    - risky_events.qmd
    - stressful_events.qmd
    - positive_events.qmd
    - general_wellness.qmd
    - part: "Past Use"
      chapters: 
        - past_use_psychoed.qmd
        - past_use_activities.qmd
    - part: "Craving"
      chapters: 
      - craving_psychoed.qmd
      - craving_activities.qmd
      chapters: 
        - future_efficacy_psychoed.qmd
        - future_efficacy_activities.qmd
      - part: "Risky location"
        chapters:
        - risky_location_psychoed.qmd
        - risky_location_activities.qmd


