---
title: "affect_arousal"
format: html
editor: visual
---

## Current feeling

"How are you feeling right now?"

2 questions: 1 unpleasant happy - 11 pleasant/happy and 1 calm/sleepy - 11 aroused/alert

Assumed direction: probably most important if unpleasant/unhappy and calm/sleepy (depressed/low energy) or unplesant/unhappy and high arousal (anxiety)

Can consider if we want to have depressed/low energy map with increasing positive events, separate module that is anxiety? Or one feelings module that provides psychoeducation about role of emotion, cognition, physiology in current experience

MATRIX

### Can You Recognize Your Feelings? 

Sometimes people don’t allow themselves to have certain emotions (for example, you tell yourself, “Feeling angry is not all right”). Sometimes people aren’t honest with themselves about their emotions (for example, saying, “I’m just having a bad day,” when the truth is they’re sad). When you mislabel emotions or deny them, you cannot address them and they build up inside you.

### Are You Aware of Physical Signs of Certain Feelings? 

Maybe you get an upset stomach when you are anxious, bite your fingernails when you are stressed, or shake when you are angry. Think about the emotions that trouble you, and try to identify how they show physically.

### How Do You Cope With Your Feelings Now? 

How do you respond when you experience negative emotions? How do your feelings affect you and others around you? For instance, do your feelings interfere with your relationships with others? Do people avoid you, try to keep you from getting upset, or try to make you feel better? Focus on one or two emotions you need to cope with better.

### How Do You Express Your Emotions? 

It is important to find an appropriate way to express emotions. You can express feelings indirectly (to a trusted group, friend, or counselor), or you can express feelings directly to others about whom you have the feelings. You need to learn in which situations it is appropriate to express feelings directly. You also can change your thinking in ways that result in your feeling different. For example, instead of saying, “I am so angry she doesn’t agree with me, I feel like using,” you can frame your feelings as, “It’s all right for someone not to agree with me, and using will not make anything better.” Do not let out-of-control feelings drive you back to using. Learning to cope with emotions means allowing yourself to feel and balancing an honest response with intelligent behavior.

## Depression –

Although we know drug use and depression are related, it is not always clear how the two interact. Most people in recovery report having problems with depression from time to time. Depression can be a particular problem for people who have been using stimulants. Stimulants make people feel “high” by flooding the brain with chemicals called neurotransmitters that regulate feelings of pleasure. During recovery there are periods when the brain doesn’t supply enough of those neurotransmitters. The undersupply of neurotransmitters causes a temporary feeling of depression. But this is different from being clinically depressed. For some people, depression left untreated can result in relapse. It is important to be aware of signs of depression and be prepared to cope with the feelings. If you feel that you cannot cope with your depression or if your depression lasts for a long time, seek help from a mental health professional. Your counselor or someone else at your treatment program can refer you to someone for help.

These are some symptoms that might indicate depression:

-   Low energy

-   Overeating or not eating

-   Sad thoughts

-   Losing interest in career or hobbies

-   Sleeping more than usual

-   Decreased sex drive □ Increased thoughts of drinking

-   Insomnia

-   Stopping attendance at 12-Step or mutual-help meetings

-   Stopping exercise program

-   Avoiding social activities

-   Feelings of boredom, irritability, or anger

-    Crying spells □ Suicidal thoughts or actions

-   Stopping normal activities such as work, cleaning house, buying groceries

Option #2:

Negative and positive emotions have an impact on the way you act and feel, which means that depression and anger can affect the choices you make and your behaviors.

Depression, anger, and addiction are issues that are closely related. According to the National Institute on Drug Abuse, people with [substance abuse disorders](https://americanaddictioncenters.org/rehab-guide/substance-use-disorder) often have co-occurring mental health issues, and vice versa.^1^ If you or someone you care about is affected by mental health issues and substance misuse, know that addiction treatment can help you [overcome addiction](https://americanaddictioncenters.org/rehab-guide/overcoming-addiction) and improve your overall mental health.

## **How Do Emotions Affect Addiction?**

When you feel happy, you are more likely to feel positive and make healthier or more constructive choices; whereas, if you feel negative, you may be more inclined to engage in negative behaviors and make poorer choices. People who experience mental wellness can cope with stress and make better decisions; whereas, mental illness or poor mental health can lead to problems with thinking, mood, and behavior.^2^

Poor mental health and addiction are mutually reinforcing—that is to say, when you feel bad, you may feel more inclined to misuse substances. Research has shown that emotional dysregulation (meaning an inability to control your responses to stimuli) can not only be a risk factor for addiction, alcohol use disorder, and depression, but also cause increased emotional problems. In addition, long-term drug use can impair your ability to deal with intense emotions and cause further emotional dysregulation.^3^

Research has also shown that alcohol, drugs, and [mental health](https://americanaddictioncenters.org/co-occurring-disorders) disorders are strongly intertwined. Disorders and behaviors such as depression, aggressiveness, and anger are correlated with a higher likelihood of substance and alcohol misuse.^4^ A recent study found that [alcohol and depression are closely linked](https://americanaddictioncenters.org/alcohol/risks-effects-dangers/depression), with sadness being a strong predictor of addiction.^5^

## **Exploring The Relationship Between Depression and Addiction**

Everyone feels blue or down from time to time, but that doesn’t necessarily mean that they have depression. Depression is a serious mental health condition that requires medical care because it can worsen if left untreated.^6^

Depression occurs when you experience obvious negative changes in mood, thought processes, and motivation that last for at least two weeks and affect your ability to function.^7^ There are different types of depressive disorders, including major depression, postpartum depression, bipolar disorder, and seasonal affective disorder.^8^

[Major depressive disorder](https://americanaddictioncenters.org/co-occurring-disorders/depressive-disorders/major) is a clinical disorder that involves experiencing symptoms of depressed mood and loss of interest for at least 2 weeks.^9^ The signs and symptoms of depression include:^8^

-   Appetite and sleep changes.

-   Fatigue or low energy.

-   Feeling chronically sad, empty, or anxious.

-   Feeling guilty, worthless, or helpless.

-   Feeling hopeless or pessimistic.

-   Feelings of restlessness.

-   Having trouble concentrating or remembering things.

-   Irritability.

-   Loss of interest in activities you once enjoyed.

-   Thoughts of suicide or self-harm.

-   Unexplained aches and pains.

    [Depression and substance misuse or alcohol use disorder](https://americanaddictioncenters.org/co-occurring-disorders/depressive-disorders) often co-occur, but the exact biological reasons for this are not entirely clear.^10^ People make choices for different reasons, so the reasons why one person becomes addicted and another doesn’t can vary. Regardless, studies confirm the link between substance misuse and depression; furthermore, depressed people may be more inclined to misuse alcohol.^10^ Depression symptoms may subside when people stop drinking, but finding the motivation to enter treatment can be difficult.^11^

    Different types of depression may lead to an increased risk of substance misuse, although clinical studies have demonstrated mixed results.^9^ In particular, people with major depression are twice as likely to have a substance use disorder than people without a mood disorder, and people with bipolar disorder are 7 times more likely to suffer from addiction.^9^ One study of lifetime prevalence rates showed that, among people who were diagnosed with a mood disorder, 32% had a co-occurring substance use disorder (SUD). Among those who had major depression, 16.5% had an alcohol use disorder and 18% had a drug use disorder; out of those who had bipolar disorder, 56% had a lifetime SUD.^9^

    In addition to underlying genetic factors, depression and addiction may be so closely related because many people self-medicate with drugs or alcohol as a way of managing their depressive symptoms.^9^ However, instead of making things better, it often only exacerbates the issue, and depression and alcohol use can both spiral out of control.^9^

    Someone who experiences depression and addiction displays symptoms of depression as well as addiction, the combination of which is known as a co-occurring disorder. Additionally, people with co-occurring disorders are at higher risk of suicide attempts.^11^ Luckily, symptoms of depression and symptoms of addiction can both be effectively addressed in rehab.^12^

## **Exploring The Relationship Between Addiction & Anger**

Anger is a human emotion that can occur in response to discomfort and is seen as a predictor of aggressive behavior. People with high levels of aggression often display more verbal and physical aggression toward other people and may have higher risks of mental illness.^13^

Different types of anger can affect you in different ways and cause various signs and symptoms. Some clinicians believe that there are 3 main types of anger, including:^14^

-   **Passive aggression,** which means you feel angry but act out your anger in passive ways because you fear confrontation, such as giving people the silent treatment or saying everything is fine when it’s not.

-   **Open aggression,** which stems from a need to feel in control. In this form of anger, you may lash out because of feelings of rage and become physically or verbally violent and aggressive. You might engage in bullying, yelling, blackmailing, or criticizing others.

-   **Assertive anger,** which is thought to be the healthiest form of anger. You act maturely and respectfully toward others, talk about your feelings, and listen to others instead of acting out.

[Anger and substance misuse are strongly correlated](https://americanaddictioncenters.org/rehab-guide/addiction-and-violence). One study of incarcerated adolescents showed that outwardly expressed anger was significantly related to marijuana and alcohol use.^15^ Another study showed that 40% of cocaine users suffered from different levels of aggression.^13^
