---
title: "craving"
format: html
editor: visual
---

# Craving

As you change your drinking, it’s normal and common to have urges or a craving for alcohol. The words “urge” and “craving” refer to a broad range of thoughts, physical sensations, or emotions that tempt you to drink, even though you have at least some desire not to. You may feel an uncomfortable pull in two directions or sense a loss of control.

Fortunately, urges to drink are **short-lived**, **predictable**, and **controllable**. With time, and by practicing new responses, you’ll find that your urges to drink will lose strength, and you’ll gain confidence in your ability to deal with urges that may still arise at times.

Here are some important facts about craving to keep in mind as you begin to work with identifying and coping with urges during recovery:

## What are cravings?

Broadly, craving refers to a strong desire to use alcohol or other drugs that, if unfulfilled, produces an often powerful degree of physical and/or mental suffering. Cravings are the result of long-term alcohol and/or other drug use and can continue for some time after the use has stopped. People with a history of heavier use might experience stronger or more frequent urges. **Experiencing cravings is a normal part of recovery and is common across all stages of recovery**.

Cravings and urges can show up in many ways, such as:

-   Physical sensations (e.g., sweating, heart racing, queasy stomach)

-   Thoughts (e.g., “A drink sounds good right now”, “I’d rather be with my friends getting drunk tonight”)

-   Positive expectancies (e.g., “I would have more fun if I was drinking”)

-   Emotions (e.g., anxiety, depression, irritability)

-   Behaviors (e.g., pausing while passing the beer display in a store, hanging out in bars or with others who are drinking).

## Cravings are PREDICTABLE

Cravings can occur in response to triggers (e.g. being around people or situations that remind someone of past alcohol use) or withdrawal (stopping regular use of alcohol).

Withdrawal: Our brains begin to regulate themselves with alcohol. Without it, the brain makes chemical demands and requests for alcohol. You can expect cravings from withdrawal to be present at the beginning of recovery and diminish over time

Triggers have to do with our memories of alcohol. Alcohol and other drugs flood our brain with reward chemicals like dopamine. Long after our last drink, our brains and memories still associate drinking with this flood of reward. When we're exposed to a cue or stimulus that triggers those latent memories, our brains beg us for more reward chemicals. And thus a craving is born.

Cravings can be internal or external:

**Internal Situations:**

-   Unpleasant emotions (e.g., frustration, depression, anger, feeling “stressed out”)

-   Pleasant emotions (e.g., joy, excitement)

-   Physical feelings (e.g., sick, shaky, tense, in pain)

-   Thoughts about drinking (e.g., “I’ll feel better if I get drink”)

**External Situations**

-   Exposure to alcohol (e.g. alcohol in the home)

-   Smell, sight and sounds of other people drinking

-   Particular times during the day when drinking used to occur (e.g., getting off work, weekends, payday)

-   Stimuli previously associated with drinking (e.g., wine glasses, bar, , ATM machine)

-   Stimuli previously associated with withdrawal (e.g., hospital, aspirin, morning)

**The more we learn to better identify our cravings, the better we can predict them**

## Cravings are TEMPORARY

Though the experience of cravings may be incredibly intense, it is important to remember that cravings are time-limited and WILL PASS. Most cravings last only a few minutes.

A craving is just like a wave at the beach. Every wave in a set starts off small, builds up to its highest point, and then breaks and flows away to shore. Each individual wave never lasts more than a few minutes. A craving is just the same. It starts off small and then builds up. But it peaks, just like a wave, and will eventually break and disappear. This whole process usually doesn’t last more than minutes. Cravings are time-limited.

Cravings will lose their power if they are not reinforced by using or drinking in response. Even if use occurs only once in a while, it will still keep those cravings alive. Cravings are like stray animals – keep feeding them and they will keep coming back. So in a very real sense these cravings are controllable.

Cravings tend to be stronger earlier on, then weaken, and eventually fade over time.

Each time a person does something other than drink and/or use others drugs, the craving loses power.

Stopping alcohol and other drug use completely is the quickest way to get rid of the cravings.
