---
title: "module_demo"
format: html
editor: visual
---

## Current idea:

-   Modules structured around predictor

    -   Addition of one extra module that is general well being focused to represent no important/predictive features

    -   Need to look in data to confirm that no negative/positive direction features are important for lapse risk (modules structured around most predictive features are in expected direction for risk)

    -   Need to GPS predictors to see if this still makes sense

    -   Discuss pros and cons of predictor defined modules vs therapeudic class (e.g. mindfulness, motivation enhancement, urge surfing) defined modules

-   First time getting a module, recommendation is read module landing page (psychoeducation)

-   Continuing questions

    -   Different modules needed for high vs low levels of predictors?

## Example: Craving

As you change your drinking, it’s normal and common to have urges or a craving for alcohol. The words “urge” and “craving” refer to a broad range of thoughts, physical sensations, or emotions that tempt you to drink, even though you have at least some desire not to. You may feel an uncomfortable pull in two directions or sense a loss of control.

Fortunately, urges to drink are **short-lived**, **predictable**, and **controllable**. With time, and by practicing new responses, you’ll find that your urges to drink will lose strength, and you’ll gain confidence in your ability to deal with urges that may still arise at times.

Here are some important facts about craving to keep in mind as you begin to work with identifying and coping with urges during recovery:

1.  What are cravings?

Broadly, craving refers to a strong desire to use alcohol or other drugs that, if unfulfilled, produces an often powerful degree of physical and/or mental suffering. Cravings are the result of long-term alcohol and/or other drug use and can continue for some time after the use has stopped. People with a history of heavier use might experience stronger or more frequent urges **Experiencing cravings is a normal part of recovery and is common across all stages of recovery.**

Cravings and urges can show up in many ways, such as:

-   **Physical sensations** (e.g., sweating, heart racing, queasy stomach)

-   **Thoughts** (e.g., “A drink sounds good right now”, “I’d rather be with my friends getting drunk tonight”)

-   **Positive expectancies** (e.g., “I would have more fun if I was drinking”)

-   **Emotions** (e.g., anxiety, depression, irritability)

-   **Behaviors** (e.g., pausing while passing the beer display in a store, hanging out in bars or with others who are drinking).

    2.  Cravings are **PREDICTABLE**

    Cravings can occur in response to triggers (e.g. being around people or situations that remind someone of past alcohol use) or withdrawal (stopping regular use of alcohol).

    1.  Withdrawal: Our brains begin to regulate themselves with alcohol. Without it, the brain makes chemical demands and requests for alcohol. You can expect cravings from withdrawal to be present at the beginning of recovery and diminish over time

    2.  Triggers have to do with our memories of alcohol. Alcohol and other drugs flood our brain with reward chemicals like dopamine. Long after our last drink, our brains and memories still associate drinking with this flood of reward. When we're exposed to a cue or stimulus that triggers those latent memories, our brains beg us for more reward chemicals. And thus a craving is born.

        Cravings can be internal or external:

    **Internal Situations:**

    -   Unpleasant emotions (e.g., frustration, depression, anger, feeling “stressed out”)

    -    Pleasant emotions (e.g., joy, excitement)

    -   Physical feelings (e.g., sick, shaky, tense, in pain)

    -   Thoughts about drinking (e.g., “I’ll feel better if I get drink”)

        **External Situations**

    -   Exposure to alcohol (e.g. alcohol in the home)

    -    Smell, sight and sounds of other people drinking

    -   Particular times during the day when drinking used to occur (e.g., getting off work, weekends, payday)

    -   Stimuli previously associated with drinking (e.g., wine glasses, bar, , ATM machine)

    -   Stimuli previously associated with withdrawal (e.g., hospital, aspirin, morning)

        **The more we learn to better identify our cravings, the better we can predict them**

-   <div>

    3.  Cravings are **TEMPORARY**

    </div>

    Though the experience of cravings may be incredibly intense, it is important to remember that cravings are time-limited and WILL PASS. Most cravings last only a few minutes.

    A craving is just like a wave at the beach. Every wave in a set starts off small, builds up to its highest point, and then breaks and flows away to shore. Each individual wave never lasts more than a few minutes. A craving is just the same. It starts off small and then builds up. But it peaks, just like a wave, and will eventually break and disappear. This whole process usually doesn’t last more than minutes. Cravings are time-limited.

Cravings will lose their power if they are not reinforced by using or drinking in response. Even if use occurs only once in a while, it will still keep those cravings alive. Cravings are like stray animals – keep feeding them and they will keep coming back. So in a very real sense these cravings are controllable.

Cravings tend to be stronger earlier on, then weaken, and eventually fade over time.

Each time a person does something other than drink and/or use others drugs, the craving loses power.

Stopping alcohol and other drug use completely is the quickest way to get rid of the cravings.

## Modules

1.  **Past Use**

    "Have you drank any alcohol that you have not yet reported?"

    Assumed direction: Yes

    Landing page - psychoeducation about role of lapses in AUD treatment, common pitfalls

2.  **Abstinence goal**

    "Is your goal still to remain abstinent in the future?"

    Assumed direction: No or Uncertain

    Landing page - Patterns of motivation in AUD treatment, importance of maintaining motivation

3.   **Craving**

    "Since your last survey, how intense was your greatest urge to drink alcohol?"

    Assumed direction: Non-zero (0 - 12 scale)

    Landing page - Important features of craving that play a role in recovery

4.  **Past risky situations**

    "Since your last survey, did you encounter any **risky situations** (people, places, or things)? If yes, rate the intensity of the situation. If you experienced more than one **risky situation**, rate the most intense one."

    Assumed direction: non-zero (0 - 12)

    Landing page - Psychoeducation about linking risky situations to emotional, physiological, cognitive experience. Goal is to ground their experience and develop ability to reflect and recognize patterns (Learn to recognize triggers)

5.  **Future risky situations**

    "How likely are you to encounter risky situations (people, places, or things) within the next week?

    Assumed direction: non-zero (1 - 11)

    Landing page - importance of planning for risky situations and common pitfalls (What to do when you recognize a trigger)

6.  **Past stressful event**

    "Since your last survey, has a hassle or stressful event occurred? If yes, rate the intensity of the event. If you experienced more than one hassle or stressful event, rate the most intense one."

    Assumed direction: non-zero (0 - 12)

    Landing page - Psychoeducation about role of stress in recovery, importance of measuring and making time for stress reduction

7.  **Future stressful events**

    "How likely are you to encounter a stressful event within the next week?

    Assumed direction: non-zero (1 - 11)

    Landing page - avoidable vs unavoidable stressor psychoeducation, normalization/reframing of stress, planning for stress reduction before/after

8.  **Past positive event**

    "Since your last survey, has a pleasant or positive event occurred? If yes, rate the intensity of the event. If you experienced more than one pleasant or positive event, rate the most intense one."

    Assumed direction: 0 or low (0 - 12) though also potential for pleasant events to increase use

    Might want to consider including a likelihood of future positive events?

    Landing page - Psychoeducation about common difficulty finding positive activities/people separate from past use patterns, role of behavioral activation, increase motivation for self care

9.  **Current feeling**

    "How are you feeling right now?"

    2 questions: 1 unpleasant happy - 11 pleasant/happy and 1 calm/sleepy - 11 aroused/alert

    Assumed direction: probably most important if unpleasant/unhappy and calm/sleepy (depressed/low energy) or unplesant/unhappy and high arousal (anxiety)

    Can consider if we want to have depressed/low energy map with increasing positive events, separate module that is anxiety? Or one feelings module that provides psychoeducation about role of emotion, cognition, physiology in current experience

10. **Future use**

    "How likely are you to drink any alcohol within the next week"

    Assumed direction: Positive (1 very unlikely - 11 very likely)

    Landing page: Can consider using same landing page for importace of motivation in AUD treatment, or this landing page provides an overview of rationale behind relapse prevention

11. **Low risk/no predictors**

    Landing page: Importance of maintaining physical and mental health, reflection on past wins to keep motivation, common pitfalls when things are going well
