---
title: "stressful_events"
format: html
editor: visual
---

# Stressful events

**Past stressful event**

"Since your last survey, has a hassle or stressful event occurred? If yes, rate the intensity of the event. If you experienced more than one hassle or stressful event, rate the most intense one."

Assumed direction: non-zero (0 - 12)

Landing page - Psychoeducation about role of stress in recovery, importance of measuring and making time for stress reduction

**Future stressful events**

"How likely are you to encounter a stressful event within the next week?

Assumed direction: non-zero (1 - 11)

Landing page - avoidable vs unavoidable stressor psychoeducation, normalization/reframing of stress, planning for stress reduction before/after

From MATRIX

Stress is a physical and emotional response to difficult or upsetting events, particularly those that continue for a long time. Stress is the experience people have when the demands they make on themselves or those placed on them disrupt their lives. Sometimes we are unaware of this emotional state until the stress produces physical symptoms. Place a checkmark next to any of the following problems you have experienced in the past 30 days: □ Sleep problems (for example, difficulty falling asleep, waking up off and on during the night, nightmares, waking up early and being unable to fall back to sleep) □ Headaches □ Irritability □ Stomach problems □ Difficulty concentrating □ Chronic illness □ General dissatisfaction with life □ Fatigue □ Feeling overwhelmed □ Moodiness If you checked two or more of these items, you may need to make some changes in your life to reduce the level of stress. Becoming more aware of stress is the first step to reducing it. You may have been accustomed to turning to substance use in times of stress. Learning new ways to cope with stress is part of the recovery process. Another Relapse Prevention session will address techniques for reducing stress.
