# Support Module Matrix


This document will describe (in brief) the relevant support modules that could be recommended for each potentially important risk featured (at times sub-divided by lapse probability).   There will be a section for each risk feature. Start with risk features based on the EMA items and we can later add features from GPS as those models are trained.   Risk features can be organized as second level headings.   Third level  headings can be used for sub-categories based on lapse probability.   The content in each "cell" can be the name of a module and a link to a qmd in the /modules folder that either further describes the support or eventually contains the actual content that would be presented.

# Questions
High low vs categorical levels of items?


## EMA item 1 Past Use
"Have you drank any alcohol that you have not yet reported)


### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability


## EMA item 1.5 Abstinence
"Is your goal still to remain abstinent in the future?" 
A: No, uncertain, yes


### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability


## EMA item 2 Urge
"...How intense wa your greatest urge to drink alcohol"
A 0 - 12, mild, mod, strong

### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability

## EMA item 3 Risky situation
"...rate most instense"
A 0 - 12, no risks, mild, mod, strong

### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability

## EMA item 4 Hassle/stressful event
"...rate most intense"
A 0 - 12, no events, mild, mod, strong

### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability


## EMA item 5 Pleasant event
"...rate most intense"
A 0 - 12, no events, mild, mod, strong

### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability


## EMA item 6 Current feeling: Valance

A: 1 unpleasant/unhappy - 11 pleasant/happy

### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability


## EMA item 7 Current feeling: Arousal

A: 1 calm/sleepy - 11 aroused/alert

### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability


## EMA item 8 Future risky situation in the next week (morning survey only)

A: 1 very unlikely - 11 very likely. very unlikely, unlikely, likely, very likely

### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability


## EMA item 9 Future stressfull event in the next week (morning survey only)

A: 1 very unlikely - 11 very likely. very unlikely, unlikely, likely, very likely

### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability


## EMA item 10 Future alcohol use in the next week (morning survey only)

A: 1 very unlikely - 11 very likely. very unlikely, unlikely, likely, very likely

### High lapse probability (only if needed to sub divide)

### Moderate lapse probability

### Low lapse probability





