---
title: "cravings reading and log"
format: html
---

## Craving Plan

The easiest way to deal with cravings and urges is to try to avoid them in the first place.This can be done by reducing your exposure to craving triggers (getting rid of alcohol in the house, not going to parties or bars, reducing contact with friends who drink, and so on).

Sometimes craving cannot be avoided, and it is necessary to find a way to cope with it. There are many different strategies for coping with craving:

1.  *Get involved in some distracting activity.* Reading, a hobby, going to a movie, exercising (jogging, biking) are good examples of distracting activities. Once you get interested in something else, you will find the urges go away. Another effective response to craving is eating, as most people do not feel like drinking after eating a big meal or something very sweet.

2.  *Talk it through.* Talk to friends or family members about craving when it occurs. Talking about cravings and urges can be very helpful in pinpointing the source of the craving. Also, talking about craving often helps to discharge and relieve the feeling and will help restore honesty in your relationship. Craving is nothing to feel bad about.

3.  *Urge surf.* Many people try to cope with their urges by gritting their teeth and toughing it out. Some urges, especially when you first return to your old drinking environment, are just too strong to ignore. When this happens, it can be useful to stay with your urge to drink until it passes. This technique is called urge surfing.

    Urges are a lot like ocean waves. They are small when they start, grow in size, and then break up and dissipate. You can imagine yourself as a surfer who will ride the wave, staying on top of it until it crests, breaks, and turns into less powerful, foamy surf. The idea behind urge surfing is similar to the idea behind many martial arts. In judo, one overpowers an opponent by first going with the force of the attack. By joining with the opponent’s force, one can take control of it and redirect it to one's advantage. This technique of gaining control by first going with the opponent also allows one to take control while expending minimal energy. Urge surfing is similar. You can initially join with an urge (as opposed to meeting it with a strong opposing force) as a way of taking control of it. <!--link to urge_surfing.qmd-->

4.  *Challenge your thoughts.* When experiencing a craving, many people have a tendency to remember only the positive effects of alcohol and often forget the negative consequences of drinking. Therefore, when experiencing craving, many people find it helpful to remind themselves of the benefits of not drinking and the negative consequences of drinking. This way, you can remind yourself that you really won’t “feel better if you just have one drink,” and that you stand to lose a lot by drinking. Sometimes its helpful to have the benefits and consequences listed on a small card that you can keep with you. Many people also find it helpful to use self-talk to constructively challenge self-statements about urges. <!--link to self_talk.qmd-->

::: callout
Make up a craving plan. Pick two or three of the general strategies that were discussed and make up a plan about how you would put them into practice if you experience an urge. Remember, cravings can come when you least expect them!

For example, if you think getting involved in a distracting activity would be helpful, which activities would you pick? Are these available to you now? Which may take some preparation? If you were feeling craving, who would be best for you to call? If you have not tried urge surfing before, it might be very helpful to practice when you are not experiencing strong cravings before trying it when facing an urge.
:::
