---
title: "abstinence_goal"
format: html
---

# Abstinence goal

Have you been able to stop using alcohol completely? At about 6 weeks into the recovery process, many people return to alcohol use. Has your addicted brain played with the idea? These are some of the most common arguments against stopping the use of alcohol and answers to the arguments. I came here to stop using speed, not to stop drinking. Part of stopping methamphetamine use is stopping all substance use, including alcohol use. I’ve had drinks and not used, so it doesn’t make any difference. Drinking over time greatly increases the risk of relapse. A single drink does not necessarily cause relapse any more than a single cigarette causes lung cancer. However, with continued drinking, the risks of relapse greatly increase. Drinking actually helps. When I have a craving, a drink calms me down, and the craving goes away. Alcohol interferes with the brain’s chemical healing process. Continued alcohol use eventually intensifies cravings, even if one drink seems to reduce cravings. I’m not an alcoholic, so why do I need to stop drinking? If you’re not an alcoholic, you should have no problem stopping alcohol use. If you can’t stop, maybe alcohol is more of a problem than you realize. I’m never going to use drugs again, but I’m not sure I’ll never drink again. Make a 6-month commitment to total abstinence. Give yourself the chance to make a decision about alcohol with a drug-free brain. If you reject alcohol abstinence because “forever” scares you, then you’re justifying drinking now and risking relapse to substance use.

Motivation for recovery

"Fear will get people into treatment, but fear alone is not enough to keep them in recovery"

Ask any group of people who are new to recovery why they want to stop using right now and you will get many different answers: ● I was arrested, and it’s either this or jail. ● My wife says if I don’t stop, we are finished. ● Last time I used I thought I was going to die; I know I’ll die if I use again. ● They are going to take the children from us unless we stop. ● I’ve been using for 20 years now; it’s time to change. Which of the people quoted is most likely to be successful in recovery? It seems logical to think that people who want to stop using for themselves and not because someone else wants them to are more likely to do well in treatment. However, that may not be true. Research shows that the reasons people stop using don’t predict whether they will be able to lead substance-free lives. What does make a difference is whether they can stay substance free long enough to appreciate the benefits of a different lifestyle. When debts are not overwhelming, relationships are rewarding, work is going well, and health is good, the person in recovery wants to stay abstinent.

Relapse justification

Once a person decides not to use drugs anymore, how does that person end up using again? Do relapses happen completely by accident? Or are there warning signs and ways to avoid relapse? Relapse justification is a process that happens in people’s minds. A person may have decided to stop using, but the person’s brain is still healing and still feels the need for the substances. The addicted brain invents excuses that allow the person in recovery to edge close enough to relapse situations that accidents can happen. You may remember a time when you intended to stay drug free but you invented a justification for using, and before you knew it, you had used again. Understanding and anticipating the justifications help you interrupt the process. Use the questions below to help you identify justifications you might be susceptible to. Substance Dependence Is Cured Has your addicted brain ever convinced you that you could use just once or use just a little? For example, have you said any of the following? ● I’m back in control. I’ll be able to stop when I want to. ● I’ve learned my lesson. I’ll only use small amounts and only once in a while. ● This substance was not my problem—stimulants were. So I can use this and not relapse. ● Other: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Testing Yourself It’s very easy to forget that being smart, not being strong, is the key to staying abstinent. Have you ever wanted to prove you could be stronger than drugs? For example, have you said any of the following? ● I’m strong enough to be around it now. ● I want to see whether I can say “No” to drinking and using. ● I want to see whether I can be around my old friends. ● I want to see how the high feels now that I’ve stopped using. ● Other: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ Celebrating You may be encouraged by other people or your addicted brain to make an exception to your abstinence. Have you ever tried to justify using with the following thoughts? ● I’m feeling really good. One time won’t hurt. ● I’m on vacation. I’ll go back to not using when I get home. ● I’m doing so well. Things are going great. I owe myself a reward. ● This is such a special event that I want to celebrate. ● Other: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ What might you do when confronted with these excuses to use?
